return {
 --{ "bufferline.nvim", enabled = false},
 --{ "coerce.nvim", enabled = false},
 --{ "flash.nvim", enabled = false},
 --{ "lazy.nvim", enabled = false},
 --{ "LazyVim", enabled = false},
 --{ "lualine.nvim", enabled = false},
 --{ "mason-lspconfig.nvim", enabled = false},
 --{ "mini.animate", enabled = false},
 --{ "mini.pairs", enabled = false},
 --{ "noice.nvim", enabled = false},
 --{ "nui.nvim", enabled = false},
 { "nvim-treesitter", enabled = false},
 { "nvim-treesitter-textobjects", enabled = false},
 --{ "onedark.nvim", enabled = false},
 --{ "snacks.nvim", enabled = false},
 { "trouble.nvim", enabled = false},
 --{ "ts-comments.nvim", enabled = false},
 { "which-key.nvim", enabled = false},
 --{ "yanky.nvim", enabled = false},
}
